# Generated by Django 4.1.7 on 2023-06-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_studentname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentname',
        ),
    ]
