# Generated by Django 4.1.7 on 2023-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markssheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Percentage', models.FloatField()),
            ],
        ),
    ]
